FROM node:18-alpine
ARG POSTGRES_URL

ADD ./package-lock.json 	/app/package-lock.json
ADD ./package.json 			/app/package.json
ADD ./tsconfig.json 		/app/tsconfig.json
ADD ./.eslintrc.js 			/app/.eslintrc.js
ADD ./prisma/				/app/prisma/

RUN echo "POSTGRES_URL=$POSTGRES_URL" > /app/prisma/.env

WORKDIR /app/

EXPOSE 3000

RUN npm run restore-all

RUN npx prisma generate

ADD ./src /app/src

RUN npm run build

CMD ["pm2-runtime", "./dist/server.js"]